import '../globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'My test site',
  description: 'Generated by Next & Sanity',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
